[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"

[licenses]
allow = [ "MIT", "Apache-2.0" ]
exceptions = []

[bans]
multiple-versions = "deny"
wildcards = "deny"

skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
# List of URLs for allowed Git repositories
allow-git = []

[graph]
all-features = true
exclude-dev = true # Remove this when softbuffer is updated to v0.4
